import { NextResponse } from "next/server";
import prisma from "../../../../prisma";

const hindiQuesitons = [
    {
        slug: "hindi-vyakaran-question-1",
        name: "कृपया 'गया' का सही वाक्यांतर करें।",
        options: [
            "मैं बाजार गया।",
            "तुम खेत गया।",
            "हम स्कूल गया।",
            "तुम्हारा दोस्त गया।",
        ],
        correctOption: 1,
        difficulty: 2,
        createdAt: "2023-11-15T02:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'मैं बाजार गया।'",
    },
    {
        slug: "hindi-vyakaran-question-2",
        name: "कृपया 'रहा' या 'रही' का सही रूप चुनें: वह बहुत दिन से वहाँ ______ है।",
        options: ["रहा", "रही", "रहता", "रहती"],
        correctOption: 2,
        difficulty: 3,
        createdAt: "2023-11-15T03:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'वह बहुत दिन से वहाँ रही है।'",
    },
    {
        slug: "hindi-vyakaran-question-3",
        name: "निम्नलिखित में से सही वाक्य चुनें: 'उसने खाना खाया।'",
        options: [
            "उसने खाना खायी।",
            "उसने खाने का खाया।",
            "उसने खाना खाता।",
            "उसने खाना खाती।",
        ],
        correctOption: 3,
        difficulty: 2,
        createdAt: "2023-11-15T04:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'उसने खाना खाता।'",
    },
    {
        slug: "hindi-vyakaran-question-4",
        name: "कृपया 'करता है' या 'करती है' का सही रूप चुनें: राज ______ बाजार जाता है।",
        options: ["करता है", "करती है", "करते हैं", "करती हैं"],
        correctOption: 1,
        difficulty: 3,
        createdAt: "2023-11-15T05:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'राज करता है बाजार जाता है।'",
    },
    {
        slug: "hindi-vyakaran-question-5",
        name: "कृपया 'जाएंगे' या 'जाएगीं' का सही रूप चुनें: हम कल शिमला ______।",
        options: ["जाएंगे", "जाएगीं", "जाएगा", "जाएगी"],
        correctOption: 1,
        difficulty: 2,
        createdAt: "2023-11-15T06:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'हम कल शिमला जाएंगे।'",
    },
    {
        slug: "hindi-vyakaran-question-6",
        name: "कृपया 'हो' या 'है' का सही रूप चुनें: यह बहुत आसान ______।",
        options: ["हो", "है", "होंगे", "हूँ"],
        correctOption: 2,
        difficulty: 3,
        createdAt: "2023-11-15T07:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'यह बहुत आसान है।'",
    },
    {
        slug: "hindi-vyakaran-question-7",
        name: "निम्नलिखित में से सही वाक्य चुनें: 'तुम्हारा दोस्त गाता है।'",
        options: [
            "तुम्हारा दोस्त गाता है।",
            "तुम्हारा दोस्त गाती है।",
            "तुम्हारा दोस्त गाते हैं।",
            "तुम्हारा दोस्त गातीं हैं।",
        ],
        correctOption: 1,
        difficulty: 2,
        createdAt: "2023-11-15T08:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'तुम्हारा दोस्त गाता है।'",
    },
    {
        slug: "hindi-vyakaran-question-8",
        name: "कृपया 'करें' या 'करते' का सही रूप चुनें: हमेशा अच्छा काम ______।",
        options: ["करें", "करते", "करता", "करती"],
        correctOption: 2,
        difficulty: 3,
        createdAt: "2023-11-15T09:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'हमेशा अच्छा काम करते हैं।'",
    },
    {
        slug: "hindi-vyakaran-question-9",
        name: "कृपया 'आएगी' या 'आएंगी' का सही रूप चुनें: वह कल मेरे घर ______।",
        options: ["आएगी", "आएंगी", "आएगा", "आएंगे"],
        correctOption: 1,
        difficulty: 2,
        createdAt: "2023-11-15T10:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'वह कल मेरे घर आएगी।'",
    },
    {
        slug: "hindi-vyakaran-question-10",
        name: "कृपया 'बोलता है' या 'बोलती है' का सही रूप चुनें: वह हिन्दी और अंग्रेज़ी भाषा ______।",
        options: ["बोलता है", "बोलती है", "बोलते हैं", "बोलतीं हैं"],
        correctOption: 1,
        difficulty: 3,
        createdAt: "2023-11-15T11:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'वह हिन्दी और अंग्रेज़ी भाषा बोलता है।'",
    },
    {
        slug: "hindi-vyakaran-question-11",
        name: "कृपया 'आएगा' या 'आएंगा' का सही रूप चुनें: वह रोज़ ताज़ महल ______।",
        options: ["आएगा", "आएंगा", "आएगी", "आएंगी"],
        correctOption: 2,
        difficulty: 2,
        createdAt: "2023-11-15T12:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
        explanation: "सही उत्तर: 'वह रोज़ ताज़ महल आएगा।'",
    },
    {
        slug: "hindi-vyakaran-question-12",
        name: "कृपया 'मुझे' का सही उपयोग करें एक वाक्य में।",
        options: [
            "मुझे बहुत खुशी है।",
            "मैं बहुत खुशी हूँ।",
            "मुझसे बहुत खुशी है।",
            "मैंने बहुत खुशी है।",
        ],
        correctOption: 1,
        difficulty: 2,
        createdAt: "2023-11-14T12:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-13",
        name: "'तुम' के सही स्थान पर उपयोग करें एक वाक्य में।",
        options: [
            "मैं तुम से मिला।",
            "तुम्हारा नाम क्या है?",
            "तुमने बहुत अच्छा काम किया।",
            "तुम मेरे दोस्त हो।",
        ],
        correctOption: 4,
        difficulty: 3,
        createdAt: "2023-11-14T13:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-14",
        name: "वाक्य में 'उसने' का सही उपयोग करें।",
        options: [
            "उसने खाना खाया।",
            "मैंने खाना खाया।",
            "तुमने खाना खाया।",
            "हमने खाना खाया।",
        ],
        correctOption: 1,
        difficulty: 2,
        createdAt: "2023-11-14T14:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-15",
        name: "कृपया 'वह' का सही उपयोग करें एक वाक्य में।",
        options: [
            "मैं वह किताब पढ़ता हूँ।",
            "वह बहुत खुश है।",
            "तुम वहाँ क्यों हो?",
            "वह मेरा दोस्त है।",
        ],
        correctOption: 1,
        difficulty: 3,
        createdAt: "2023-11-14T15:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-16",
        name: "वाक्य में 'हम' का सही उपयोग करें।",
        options: [
            "तुम हमसे मिले?",
            "हम बहुत खुश हैं।",
            "हम खाना खा रहे हैं।",
            "उसने हमें देखा।",
        ],
        correctOption: 2,
        difficulty: 2,
        createdAt: "2023-11-14T16:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-17",
        name: "कृपया 'इसमें' का सही उपयोग करें एक वाक्य में।",
        options: [
            "मैं इसमें विश्वास करता हूँ।",
            "वह इसमें क्या है?",
            "तुम इसमें बहुत अच्छे हो।",
            "इसमें मेरा कोई रोल नहीं है।",
        ],
        correctOption: 1,
        difficulty: 3,
        createdAt: "2023-11-14T17:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-18",
        name: "'उन्होंने' का सही उपयोग करें एक वाक्य में।",
        options: [
            "उन्होंने गाना गाया।",
            "तुमने उन्हें देखा क्या?",
            "हमने उन्हें बुलाया।",
            "मैंने उन्हें सुना।",
        ],
        correctOption: 1,
        difficulty: 2,
        createdAt: "2023-11-14T18:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-19",
        name: "वाक्य में 'उनको' का सही उपयोग करें।",
        options: [
            "उनको मेरा पता है।",
            "तुमने उनको देखा?",
            "हम उनको जानते हैं।",
            "वह उनको बुलाएगा।",
        ],
        correctOption: 3,
        difficulty: 3,
        createdAt: "2023-11-14T19:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-20",
        name: "'उसका' सही तरीके से उपयोग करें एक वाक्य में।",
        options: [
            "उसका नाम क्या है?",
            "तुमने उसका सामान देखा?",
            "हम उसका समर्थन करेंगे।",
            "उसका स्कूल कहाँ है?",
        ],
        correctOption: 2,
        difficulty: 2,
        createdAt: "2023-11-14T20:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-21",
        name: "'उससे' का सही उपयोग करें एक वाक्य में।",
        options: [
            "तुम उससे मिले क्या?",
            "वह उससे कहाँ है?",
            "हम उससे बात करेंगे।",
            "तुमने उससे सीधा पैसा लिया।",
        ],
        correctOption: 3,
        difficulty: 3,
        createdAt: "2023-11-14T21:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-22",
        name: "'उसपर' का सही उपयोग करें एक वाक्य में।",
        options: [
            "उसपर कोई शक्तिशाली है।",
            "तुमने उसपर विश्वास किया?",
            "हम उसपर आभास करते हैं।",
            "तुम उसपर क्यों हंस रहे हो?",
        ],
        correctOption: 1,
        difficulty: 2,
        createdAt: "2023-11-14T22:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
    {
        slug: "hindi-vyakaran-question-23",
        name: "'उसके साथ' का सही तरीके से उपयोग करें एक वाक्य में।",
        options: [
            "तुम उसके साथ हो?",
            "वह उसके साथ गया।",
            "हम उसके साथ खड़े हैं।",
            "तुम उसके साथ खेलोगे?",
        ],
        correctOption: 2,
        difficulty: 3,
        createdAt: "2023-11-14T23:00:00.000Z",
        languageSlug: "hindi",
        topicSlug: "vyakaran",
        userEmail: "jayant@gmail.com",
    },
];

const hindi_samvad = [
  {
    "slug": "hindi-samvad-question-1",
    "name": "दोस्त: नमस्ते, कैसे हो तुम?",
    "options": [
      "मैं ठीक हूँ, धन्यवाद",
      "मैं बहुत खुश हूँ",
      "मैं ठीक नहीं हूँ",
      "मैं ठीक हूँ, शुक्रिया"
    ],
    "correctOption": 1,
    "difficulty": 2,
    "createdAt": "2023-11-15T12:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "samvad",
    "userEmail": "jayant@gmail.com",
    "explanation": "ठीक हूँ, धन्यवाद का उत्तर सही है।"
  },
  {
    "slug": "hindi-samvad-question-2",
    "name": "माता: तुमने आज स्कूल कैसे गया?",
    "options": [
      "हाँ, मैंने गया",
      "नहीं, मैंने नहीं गया",
      "हाँ, मैं स्कूल गया",
      "नहीं, मैंने अभी तक नहीं गया"
    ],
    "correctOption": 3,
    "difficulty": 3,
    "createdAt": "2023-11-15T13:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "samvad",
    "userEmail": "jayant@gmail.com",
    "explanation": "हाँ, मैं स्कूल गया का उत्तर सही है।"
  },
  {
    "slug": "hindi-samvad-question-3",
    "name": "दोस्त: तुम्हारी पुस्तक कैसी है?",
    "options": [
      "मेरी पुस्तक अच्छी है",
      "मेरी पुस्तक बहुत बढ़िया है",
      "मेरी पुस्तक बहुत बढ़िया नहीं है",
      "मेरी पुस्तक बहुत बढ़िया थी"
    ],
    "correctOption": 2,
    "difficulty": 2,
    "createdAt": "2023-11-15T14:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "samvad",
    "userEmail": "jayant@gmail.com",
    "explanation": "मेरी पुस्तक बहुत बढ़िया है का उत्तर सही है।"
  },
  {
    "slug": "hindi-samvad-question-4",
    "name": "पिताजी: तुम्हारी पढ़ाई कैसी चल रही है?",
    "options": [
      "बहुत अच्छी",
      "ठीक",
      "बहुत बुरी",
      "सामान्य"
    ],
    "correctOption": 1,
    "difficulty": 3,
    "createdAt": "2023-11-15T15:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "samvad",
    "userEmail": "jayant@gmail.com",
    "explanation": "बहुत अच्छी का उत्तर सही है।"
  },
  {
    "slug": "hindi-samvad-question-5",
    "name": "बहन: तुमने रात को कितनी किताबें पढ़ीं?",
    "options": [
      "एक",
      "दो",
      "तीन",
      "चार"
    ],
    "correctOption": 2,
    "difficulty": 2,
    "createdAt": "2023-11-15T16:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "samvad",
    "userEmail": "jayant@gmail.com",
    "explanation": "दो का उत्तर सही है।"
  },
  {
    "slug": "hindi-samvad-question-6",
    "name": "मित्र: क्या तुम आज स्कूल जा रहे हो?",
    "options": [
      "हाँ, मैं जा रहा हूँ",
      "नहीं, मैं नहीं जा रहा",
      "हाँ, मैं जा रही हूँ",
      "नहीं, मैं नहीं जा रही"
    ],
    "correctOption": 1,
    "difficulty": 3,
    "createdAt": "2023-11-15T17:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "samvad",
    "userEmail": "jayant@gmail.com",
    "explanation": "हाँ, मैं जा रहा हूँ का उत्तर सही है।"
  },
  {
    "slug": "hindi-samvad-question-7",
    "name": "माँ: तुमने क्या खाया?",
    "options": [
      "रोटी-सब्जी",
      "मैगी",
      "दाल-चावल",
      "पिज़्ज़ा"
    ],
    "correctOption": 3,
    "difficulty": 2,
    "createdAt": "2023-11-15T18:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "samvad",
    "userEmail": "jayant@gmail.com",
    "explanation": "दाल-चावल का उत्तर सही है।"
  },
  {
    "slug": "hindi-samvad-question-8",
    "name": "दोस्त: कहाँ जा रहे हो इस सप्ताहेंड?",
    "options": [
      "दादाजी के घर",
      "मौसी के यहाँ",
      "पार्क",
      "बाजार"
    ],
    "correctOption": 4,
    "difficulty": 3,
    "createdAt": "2023-11-15T19:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "samvad",
    "userEmail": "jayant@gmail.com",
    "explanation": "बाजार का उत्तर सही है।"
  },
  {
    "slug": "hindi-samvad-question-9",
    "name": "शिक्षक: क्या तुमने अपनी होमवर्क पूरी की है?",
    "options": [
      "हाँ, मैंने की है",
      "नहीं, मैंने नहीं की है",
      "हाँ, मैंने कर ली है",
      "नहीं, मैंने बहुत कम की है"
    ],
    "correctOption": 1,
    "difficulty": 2,
    "createdAt": "2023-11-15T20:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "samvad",
    "userEmail": "jayant@gmail.com",
    "explanation": "हाँ, मैंने की है का उत्तर सही है।"
  },
  {
    "slug": "hindi-samvad-question-10",
    "name": "दोस्त: तुमने नया मोबाइल लिया क्या?",
    "options": [
      "हाँ, मैंने लिया है",
      "नहीं, मैंने नहीं लिया",
      "हाँ, मैंने ले लिया है",
      "नहीं, मैंने आज सुबह ही लिया"
    ],
    "correctOption": 3,
    "difficulty": 3,
    "createdAt": "2023-11-15T21:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "samvad",
    "userEmail": "jayant@gmail.com",
    "explanation": "हाँ, मैंने ले लिया है का उत्तर सही है।"
  }
]

const hindi_sabdavali = [
  {
    "slug": "hindi-shabdavali-question-1",
    "name": "इनमें से कौन सा शब्द विशेषण है: 'सुंदर', 'तेज', 'बड़ा', 'गहरा'?",
    "options": ["सुंदर", "तेज", "बड़ा", "गहरा"],
    "correctOption": 1,
    "difficulty": 2,
    "createdAt": "2023-11-16T12:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'सुंदर' एक विशेषण है।"
  },
  {
    "slug": "hindi-shabdavali-question-2",
    "name": "इनमें से कौन सा शब्द संज्ञा है: 'गाड़ी', 'पुस्तक', 'दुकान', 'पेड़'?",
    "options": ["गाड़ी", "पुस्तक", "दुकान", "पेड़"],
    "correctOption": 1,
    "difficulty": 3,
    "createdAt": "2023-11-16T13:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'गाड़ी' एक संज्ञा है।"
  },
  {
    "slug": "hindi-shabdavali-question-3",
    "name": "इनमें से कौन सा शब्द सर्वनाम है: 'तुम', 'यह', 'हम', 'वह'?",
    "options": ["तुम", "यह", "हम", "वह"],
    "correctOption": 1,
    "difficulty": 2,
    "createdAt": "2023-11-16T14:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'तुम' एक सर्वनाम है।"
  },
  {
    "slug": "hindi-shabdavali-question-4",
    "name": "इनमें से कौन सा शब्द क्रिया है: 'खेलना', 'पढ़ना', 'गाना', 'सोना'?",
    "options": ["खेलना", "पढ़ना", "गाना", "सोना"],
    "correctOption": 1,
    "difficulty": 3,
    "createdAt": "2023-11-16T15:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'खेलना' एक क्रिया है।"
  },
  {
    "slug": "hindi-shabdavali-question-5",
    "name": "इनमें से कौन सा शब्द अव्यय है: 'बहुत', 'हमेशा', 'यहीं', 'सुंदरता'?",
    "options": ["बहुत", "हमेशा", "यहीं", "सुंदरता"],
    "correctOption": 2,
    "difficulty": 2,
    "createdAt": "2023-11-16T16:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'हमेशा' एक अव्यय है।"
  },
  {
    "slug": "hindi-shabdavali-question-6",
    "name": "इनमें से कौन सा शब्द विराम चिह्न है: '।', '॥', '॰', '१२'?",
    "options": ["।", "॥", "॰", "१२"],
    "correctOption": 1,
    "difficulty": 3,
    "createdAt": "2023-11-16T17:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द '।' एक विराम चिह्न है।"
  },
  {
    "slug": "hindi-shabdavali-question-7",
    "name": "इनमें से कौन सा शब्द समास है: 'सुन्दर', 'सफल', 'अद्भुत', 'उत्कृष्ट'?",
    "options": ["सुन्दर", "सफल", "अद्भुत", "उत्कृष्ट"],
    "correctOption": 4,
    "difficulty": 2,
    "createdAt": "2023-11-16T18:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'उत्कृष्ट' एक समास है।"
  },
  {
    "slug": "hindi-shabdavali-question-8",
    "name": "इनमें से कौन सा शब्द अनेक भाषाओं में समान है: 'टेबल', 'किताब', 'टेलीविज़न', 'रेडियो'?",
    "options": ["टेबल", "किताब", "टेलीविज़न", "रेडियो"],
    "correctOption": 3,
    "difficulty": 3,
    "createdAt": "2023-11-16T19:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'टेलीविज़न' अनेक भाषाओं में समान है।"
  },
  {
    "slug": "hindi-shabdavali-question-9",
    "name": "इनमें से कौन सा शब्द पुलिंग है: 'फूल', 'छछूंदर', 'आसमान', 'पुस्तक'?",
    "options": ["फूल", "छछूंदर", "आसमान", "पुस्तक"],
    "correctOption": 2,
    "difficulty": 2,
    "createdAt": "2023-11-16T20:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'छछूंदर' पुलिंग है।"
  },
  {
    "slug": "hindi-shabdavali-question-10",
    "name": "इनमें से कौन सा शब्द तद्भव है: 'टेलीफ़ोन', 'टेलीविज़न', 'आइसक्रीम', 'साइकिल'?",
    "options": ["टेलीफ़ोन", "टेलीविज़न", "आइसक्रीम", "साइकिल"],
    "correctOption": 3,
    "difficulty": 3,
    "createdAt": "2023-11-16T21:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'आइसक्रीम' तद्भव है।"
  },
  {
    "slug": "hindi-shabdavali-question-11",
    "name": "इनमें से कौन सा शब्द विराम-चिह्न सहित है: 'विशेषज्ञ', 'आत्मा', 'केन्द्र', 'सामान्य'?",
    "options": ["विशेषज्ञ", "आत्मा", "केन्द्र", "सामान्य"],
    "correctOption": 1,
    "difficulty": 2,
    "createdAt": "2023-11-16T22:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'विशेषज्ञ' विराम-चिह्न सहित है।"
  },
  {
    "slug": "hindi-shabdavali-question-12",
    "name": "इनमें से कौन सा शब्द समानार्थी है: 'सुखद', 'प्रसन्न', 'खुश', 'मनोहर'?",
    "options": ["सुखद", "प्रसन्न", "खुश", "मनोहर"],
    "correctOption": 3,
    "difficulty": 3,
    "createdAt": "2023-11-16T23:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "shabdavali",
    "userEmail": "jayant@gmail.com",
    "explanation": "शब्द 'खुश' समानार्थी है।"
  }
]

const questions = [
  {
    "slug": "hindi-sahitya-question-1",
    "name": "हिन्दी साहित्य का संबंधित है?",
    "options": ["आदि काव्य", "रघुवंश", "गीता रहस्य", "महाभारत"],
    "correctOption": 2,
    "difficulty": 2,
    "createdAt": "2023-11-18T12:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "रघुवंश एक महाकाव्य है जो कवि कालिदास द्वारा रचित किया गया।"
  },
  {
    "slug": "hindi-sahitya-question-2",
    "name": "महाभारत के किस भाग में 'भगवद गीता' है?",
    "options": ["आदि पर्व", "भीष्म पर्व", "वन पर्व", "भीष्म पर्व"],
    "correctOption": 4,
    "difficulty": 3,
    "createdAt": "2023-11-18T13:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "भगवद गीता महाभारत के 'भीष्म पर्व' में है।"
  },
  {
    "slug": "hindi-sahitya-question-3",
    "name": "कवि तुलसीदास का असली नाम क्या था?",
    "options": ["सूरदास", "रैदास", "गोस्वामी तुलसीदास", "रामदास"],
    "correctOption": 3,
    "difficulty": 2,
    "createdAt": "2023-11-18T14:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "कवि तुलसीदास का असली नाम 'रामचन्द्र' था, जो बाद में 'तुलसीदास' कहलाये।"
  },
  {
    "slug": "hindi-sahitya-question-4",
    "name": "प्रेमचंद का उपनाम क्या था?",
    "options": ["धर्मवीर", "निराला", "आचार्य रामचंद", "कल्का प्रसाद"],
    "correctOption": 4,
    "difficulty": 3,
    "createdAt": "2023-11-18T15:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "प्रेमचंद का उपनाम 'कल्का प्रसाद' था।"
  },
  {
    "slug": "hindi-sahitya-question-5",
    "name": "तुलसीदास का काव्य ग्रंथ 'कवितावली' में कौन-कौन से काव्य हैं?",
    "options": ["रामचरितमानस", "कृष्णकरितानि", "सुन्दरकाण्ड", "विनयपत्रिका"],
    "correctOption": 1,
    "difficulty": 2,
    "createdAt": "2023-11-18T16:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "'कवितावली' में तुलसीदास के 'रामचरितमानस' शामिल हैं।"
  },
  {
    "slug": "hindi-sahitya-question-6",
    "name": "हिन्दी साहित्य के किस क्षेत्र के लिए 'साहित्यिक रत्न' कहा जाता है?",
    "options": ["उपन्यास", "काव्य", "गद्य", "दृश्यकला"],
    "correctOption": 2,
    "difficulty": 3,
    "createdAt": "2023-11-18T17:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "हिन्दी साहित्य के क्षेत्र में 'काव्य' के लिए 'साहित्यिक रत्न' कहा जाता है।"
  },
  {
    "slug": "hindi-sahitya-question-7",
    "name": "कवि माखनलाल चतुर्वेदी का असली नाम क्या था?",
    "options": ["राहीम", "मकरंद दावालपुरकर", "गौरीशंकर", "माखनलाल"],
    "correctOption": 4,
    "difficulty": 2,
    "createdAt": "2023-11-18T18:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "कवि माखनलाल चतुर्वेदी का असली नाम 'मकरंद गोविंद बिन्द्रे' था।"
  },
  {
    "slug": "hindi-sahitya-question-8",
    "name": "हिन्दी साहित्य का पहला काव्य ग्रंथ कौन सा है?",
    "options": ["रामचरितमानस", "सुन्दरकाण्ड", "गीता रहस्य", "सत्यार्थ प्रकाश"],
    "correctOption": 1,
    "difficulty": 3,
    "createdAt": "2023-11-18T19:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "हिन्दी साहित्य का पहला काव्य ग्रंथ है 'रामचरितमानस' जो कवि तुलसीदास द्वारा रचित हुआ।"
  },
  {
    "slug": "hindi-sahitya-question-9",
    "name": "कवि सूरदास का नाम किसे मिला था?",
    "options": ["कृष्ण भगवान", "रामचन्द्र जी", "सूर की संतान", "विष्णु भगवान"],
    "correctOption": 1,
    "difficulty": 2,
    "createdAt": "2023-11-18T20:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "कवि सूरदास का नाम 'कृष्ण भगवान' से मिला था जिनसे उन्होंने अपनी कृष्ण भक्ति कविताएँ रची।"
  },
  {
    "slug": "hindi-sahitya-question-10",
    "name": "प्रेमचंद का उपनाम 'नयायाचार्य' क्यों था?",
    "options": ["उनके न्यायशास्त्र के कारण", "उनकी न्यायप्रियता के कारण", "उनके उपन्यासों में न्याय से संबंधित", "न्यायपूर्वक उनकी रचना के कारण"],
    "correctOption": 4,
    "difficulty": 3,
    "createdAt": "2023-11-18T21:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "प्रेमचंद को 'नयायाचार्य' कहा जाता था क्योंकि उनकी रचनाएँ समाज में न्याय की बात करती थीं।"
  },
  {
    "slug": "hindi-sahitya-question-11",
    "name": "भारतीय साहित्य के किस युग में 'आदि काव्य' रचा गया था?",
    "options": ["वैदिक युग", "भक्ति युग", "रोमांटिक युग", "आधुनिक युग"],
    "correctOption": 1,
    "difficulty": 2,
    "createdAt": "2023-11-18T22:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "'आदि काव्य' वैदिक युग में रचा गया था।"
  },
  {
    "slug": "hindi-sahitya-question-12",
    "name": "महाकवि कालिदास का अधिकारी उपनाम क्या था?",
    "options": ["कविराज", "महाकवि", "कविश्रेष्ठ", "भारतीय कवि"],
    "correctOption": 1,
    "difficulty": 3,
    "createdAt": "2023-11-18T23:00:00.000Z",
    "languageSlug": "hindi",
    "topicSlug": "sahitya",
    "userEmail": "jayant@gmail.com",
    "explanation": "महाकवि कालिदास को 'कविराज' कहा जाता है।"
  }
]




export const POST = async (req, res) => {
    try {
        await prisma.question.createMany({
            data: questions,
        });

        return NextResponse.json({ success: true }, { status: 201 });
    } catch (error) {
        console.log(error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
};
